LoLClubWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eventcalendar/', include('eventcalendar.urls')),
    path('statsviewer/', include('statsviewer.urls')),
    path('', include('eventcalendar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

eventcalendar/urls.py
from django.urls import path, include
from eventcalendar import views

urlpatterns = [
    path('', views.home, name="home"  ),
    path('calendar/', views.calendar, name = "calendar"),
    path('results/', views.results, name = 'results'),
    path('rosters/', views.rosters, name = 'rosters'),
    path('officers/', views.officers, name = 'officers'),
    path('minutes/', views.minutes, name = 'minutes'),
    path('hof/', views.hof, name = 'hof'),
    #me trying to make event detail view 
    path('calendar/<int:pk>', views.eventDetailView.as_view(), name = 'event-detail'),
    path('stats/', include('statsviewer.urls')),
    path('calendar/create/', views.EventCreate.as_view(), name = 'event-create'),
    path('calendar/<int:pk>/update', views.EventUpdate.as_view(), name = 'event-update'),
    path('calendar/<int:pk>/delete', views.EventDelete.as_view(), name = 'event-delete'),
    path('results/create/', views.ResultCreate.as_view(), name = 'result-create'),
    path('results/<int:pk>', views.ResultDetailView.as_view(), name = 'result-detail'),
    path('results/<int:pk>/update', views.ResultUpdate.as_view(), name = 'result-update'),
    path('results/<int:pk>/delete', views.ResultDelete.as_view(), name = 'result-delete'),

]

statsviewer/urls.py
from django.contrib import admin
from django.urls import path, include
from statsviewer import views



urlpatterns = [
    path('stats_home', views.stats, name = 'stats-home'),
    path('stats_home/player_list/', views.playerListView, name = 'player-list'),
    path('stats_home/player/<int:pk>', views.playerDetailView.as_view(), name = 'player-detail'),
    path('stats_home/game_list/', views.gameListView, name = 'game-list'),
    path('stats_home/game/<int:pk>', views.gameDetailView.as_view(), name = 'game-detail'),

    path('', views.gohome, name = 'go-home'),
    path('stats_home/game_list/create/', views.GameCreate.as_view(), name = 'game-create'),
    path('stats_home/game/<int:pk>/update', views.GameUpdate.as_view(), name = 'game-update'),
    path('stats_home/game/<int:pk>/delete', views.GameDelete.as_view(), name = 'game-delete'),
    path('stats_home/player_list/create/', views.PlayerCreate.as_view(), name = 'player-create'),
    path('stats_home/player/<int:pk>/update', views.PlayerUpdate.as_view(), name = 'player-update'),
    path('stats_home/player/<int:pk>/delete', views.PlayerDelete.as_view(), name = 'player-delete'),
    path('stats_home/player_list/instance/create/', views.PlayerInstanceCreate.as_view(), name = 'instance-create'),
    path('stats_home/player/instance/<int:pk>/update', views.PlayerInstanceUpdate.as_view(), name = 'instance-update'),
    path('stats_home/player/instance/<int:pk>/delete', views.PlayerInstanceDelete.as_view(), name = 'instance-delete'),
    path('stats_home/player/instance/<int:pk>/', views.PlayerInstanceDetailView.as_view(), name = 'instance-detail'),
]

eventcalendar/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Event(models.Model):
    eventID = models.BigAutoField(primary_key=True)
    startTime = models.DateTimeField(blank=True)
    endTime = models.DateTimeField()
    eventName = models.CharField(default="New Event", max_length=160)
    
    def __str__(self):
        return self.eventName
    
    def get_absolute_url(self):
        return reverse("event-detail", args=[str(self.eventID)])
    



class Lan(models.Model):
    event = models.OneToOneField('Event', on_delete=models.CASCADE, null=False, primary_key=True)
    location = models.CharField(max_length=320)

class Tournament(models.Model):
    event = models.OneToOneField('Event', on_delete=models.CASCADE, null=False, primary_key=True)
    STREAM_STATUS = (
        ('m', 'Main'),
        ('a', 'Alt'),
        ('n', 'None'),
    )
    status = models.CharField(max_length=1, choices=STREAM_STATUS, blank=True, default='n', help_text='Where streamed')
    signup = models.URLField()

class Game(models.Model):
    event = models.OneToOneField('Event', on_delete=models.CASCADE, null=False, primary_key=True)
    TEAM_FIELDS = (
        ('v', 'Varsity'),
        ('j', 'Junior Varsity'),
        ('c', 'C Team'),
        ('d', 'D Team'),
        ('o', 'Other'),
    )
    team = models.CharField(max_length=1, choices = TEAM_FIELDS, blank=True, help_text= 'Team playing')
    LEAGUE_FIELDS = (
        ('c', 'CCL'),
        ('n', 'NECC'),
        ('e', 'NACE'),
        ('o', 'Other'),
    )
    league = models.CharField(max_length=1, choices=LEAGUE_FIELDS, blank=True, help_text='What League are they competing in')
    STREAM_STATUS = (
        ('m', 'Main'),
        ('a', 'Alt'),
        ('n', 'None'),
    )
    status = models.CharField(max_length=1, choices=STREAM_STATUS, blank=True, default='n', help_text='Where streamed')

class Result(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    score = models.CharField(max_length=5)
    division = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse("result-detail", kwargs={"pk": self.pk})
    
    
class Hof(models.Model):
    tourneyName = models.CharField(max_length=30)
    teamName = models.CharField(max_length=30)
    player1 = models.CharField(max_length=30)
    player2 = models.CharField(max_length=30)
    player3 = models.CharField(max_length=30)
    player4 = models.CharField(max_length=30)
    player5 = models.CharField(max_length=30)

    def __str__(self):
        return self.tourneyName

eventcalendar/views.py
from datetime import datetime
from django.shortcuts import render
from eventcalendar.models import Event, Game, Lan, Tournament, Hof, Result
from django.views import generic
from django.urls import reverse_lazy


# Create your views here.
def home(request):
    return render(request, 'home.html')

def calendar(request):
    # PASS LIST OF EVENTS THAT HAVE NOT HAPPENED

    current_datetime = datetime.now()
    events = Event.objects.filter(endTime__gte = current_datetime)
    return render(request, 'calendar.html', {'events' : events})

def results(request):
    results = Result.objects.all()
    return render(request, 'results.html', {'results' : results})

def rosters(request):
    return render(request, 'rosters.html')

def officers(request):
    return render(request, 'officers.html')

def minutes(request):
    return render(request, 'minutes.html')

def hof(request):
    hofs = Hof.objects.all()
    return render(request, 'hof.html', {'hofs' : hofs})


class eventDetailView(generic.DetailView):
    model = Event
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = self.object
        dataList = [event]
        #Create list of games, lans, tournaments with same id
        games = Game.objects.filter(event = event.eventID)
        lans = Lan.objects.filter(event = event.eventID)
        tournaments = Tournament.objects.filter(event = event.eventID)
        #If to add specific event type to dataList
        if games:
            dataList.append(games[0])
        elif lans:
            dataList.append(lans[0])
        elif tournaments:
            dataList.append(tournaments[0])
        #Create and return context
        context = {'list' : dataList}
        return context

class ResultDetailView(generic.DetailView):
    model = Result

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

class EventCreate(PermissionRequiredMixin,CreateView):
    model = Event
    fields = ['eventID', 'startTime', 'endTime', 'eventName']
    permission_required = 'eventcalendar.add_event'

class EventUpdate(PermissionRequiredMixin,UpdateView):
    model = Event
    fields = '__all__'
    permission_required = 'eventcalendar.change_event'

class EventDelete(PermissionRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('calendar')
    permission_required = 'eventcalendar.delete_event'

class ResultCreate(PermissionRequiredMixin, CreateView):
    model = Result
    fields = ['name', 'date', 'score', 'division']
    permission_required = 'eventcalendar.add_result'

class ResultUpdate(PermissionRequiredMixin, UpdateView):
    model = Result
    fields = '__all__'
    permission_required = 'eventcalendar.change_result'

class ResultDelete(PermissionRequiredMixin, DeleteView):
    model = Result
    success_url = reverse_lazy('results')
    permission_required = 'eventcalendar.delete_result'

eventcalendar/templates/eventcalendar/event_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Event: {{ event }}</h1>

<p>Are you sure you want to delete the event?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>

{% endblock %}

eventcalendar/templates/eventcalendar/event_detail.html
{% extends "base_generic.html" %}

{% block content %}



{% if list.1.league %}
<div class="row justify-content-center">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <h4 class="center"> Game Info: </h4>
        <div class="card game" style="width: 450px; margin-left: auto; margin-right: auto;">
            <div class="card-header" style="text-align: center">
                {{list.0.eventName}}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item game" style="text-align: center; border: 1px solid #FFC82E">{{list.0.startTime}} - {{list.0.endTime}}</li>
                <li class="list-group-item game" style="text-align: center; border: 1px solid #FFC82E">Team: {{list.1.get_team_display}}</li>
                <li class="list-group-item game" style="text-align: center; border: 1px solid #FFC82E">League: {{list.1.get_league_display}}</li>
                <li class="list-group-item game" style="text-align: center; border: 1px solid #FFC82E">Streamed: {{list.1.get_status_display}}</li>
            </ul>
        </div>
    </div>
<div class="col-sm-4"></div>
</div>
{% endif %}

{% if list.1.location %}
<div class="row justify-content-center">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <h4 class="center"> LAN Info: </h4>
        <div class="card lan" style="width: 450px; margin-left: auto; margin-right: auto;">
            <div class="card-header" style="text-align: center">
                {{list.0.eventName}}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item lan" style="text-align: center; border: 1px solid #FFC82E">{{list.0.startTime}} - {{list.0.endTime}}</li>
                <li class="list-group-item lan" style="text-align: center; border: 1px solid #FFC82E">Location: {{list.1.location}}</li>
            </ul>
        </div>
    </div>
<div class="col-sm-4"></div>
</div>
{% endif %}

{% if list.1.signup %}
<div class="row justify-content-center">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <h4 class="center"> Tournament Info: </h4>
        <div class="card tournament" style="width: 450px; margin-left: auto; margin-right: auto;">
            <div class="card-header" style="text-align: center">
                {{list.0.eventName}}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item tournament" style="text-align: center; border: 1px solid crimson">{{list.0.startTime}} - {{list.0.endTime}}</li>
                <li class="list-group-item tournament" style="text-align: center; border: 1px solid crimson">Streamed: {{list.1.get_status_display}}</li>
            </ul>
        </div>
        <div class="col text-allign: center">
        <a type="button" class="btn btn-primary btn-lg tournament" href="{{ list.1.signup }}" target="_blank">Sign up!</a>
        </div>
    </div>

<div class="col-sm-4"></div>
</div>
{% endif %}


{% if user.is_authenticated %}
<li><a href="{% url 'event-update' list.0.eventID %}">Update event</a></li>
<li><a href="{% url 'event-delete' list.0.eventID %}">Delete event</a></li>
{% endif %}

{% endblock %}

eventcalendar/templates/eventcalendar/event_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

eventcalendar/templates/eventcalendar/result_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Result: {{ result }}</h1>

<p>Are you sure you want to delete the result?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>

{% endblock %}

eventcalendar/templates/eventcalendar/result_detail.html
{% extends 'base_generic.html' %}
{% block content %}

{% if user.is_authenticated%}
<li><a href="{% url 'result-update' result.id %}">Update result</a></li>
<li><a href="{% url 'result-delete' result.id %}">Delete result</a></li>
{% endif %}

{% endblock %}

eventcalendar/templates/eventcalendar/result_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}